channels:
  - conda-forge
dependencies:
  - doit=0.33.1
  - python=3.7
  - paraview=5.9.1
  - tectonic=0.8.0
  - gmsh=4.6.0
  - fenics=2019.1.0
  - meshio=4.3.1
  - importlib_metadata=4.8.1
  - superlu_dist=6.2.0
